#ifndef _TINYLOG_SHA1_H_
#define _TINYLOG_SHA1_H_
#include <cstring>
#include <cstdint>

/* Generated by Copilot */

namespace secure{

class SHA1 {
public:
    SHA1();
    void update(const uint8_t* data, uint64_t len);

    void final(uint8_t* hash);

    static bool compute_sha1(const uint8_t* in, size_t in_len, uint8_t* out, size_t out_size);
    static const size_t SHA1_OUT_SIZE;

private:
    uint32_t leftRotate(uint32_t x, uint32_t c);
    void transform();
    void reset();

    uint32_t state_[5];
    uint64_t bitlen_;
    uint8_t data_[64];
    uint32_t datalen_;
};

}
#endif // _TINYLOG_SHA1_H_